# Generated by Django 4.0.2 on 2022-03-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='address',
            field=models.CharField(default='addy', max_length=200),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidding_settings',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='default', max_length=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='company_name',
            field=models.CharField(default='company', max_length=200),
        ),
        migrations.AddField(
            model_name='bid',
            name='dob',
            field=models.DateField(default='2022-03-02'),
        ),
        migrations.AddField(
            model_name='bid',
            name='first_name',
            field=models.CharField(default='first_name', max_length=200),
        ),
        migrations.AddField(
            model_name='bid',
            name='last_name',
            field=models.CharField(default='last_name', max_length=200),
        ),
        migrations.AddField(
            model_name='bid',
            name='telephone',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
